//package com.example.mobilebrowser.classifier
//
//import android.content.Context
//import org.json.JSONObject
//
///**
// * Standard-scaler generated by scripts/build_dataset.py.
// */
//class Scaler(ctx: Context) {
//    private val mean: FloatArray
//    private val scale: FloatArray
//
//    init {
//        val json = ctx.assets.open("scaler.json").bufferedReader().use { it.readText() }
//        val obj  = JSONObject(json)
//        mean  = FloatArray(obj.getJSONArray("mean").length()) { i ->
//            obj.getJSONArray("mean").getDouble(i).toFloat()
//        }
//        scale = FloatArray(obj.getJSONArray("scale").length()) { i ->
//            obj.getJSONArray("scale").getDouble(i).toFloat()
//        }
//    }
//
//    /** (x - mean) / scale, element-wise. */
//    fun normalize(x: FloatArray): FloatArray =
//        FloatArray(x.size) { i -> (x[i] - mean[i]) / scale[i] }
//}
