package com.example.mobilebrowser.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.Date

// Represents a single bookmark entry in the database.
@Entity(tableName = "bookmarks")
data class BookmarkEntity(
    // Unique identifier for each bookmark, automatically generated by Room.
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    val title: String,

    val url: String,

    // Optional field to store the favicon of the bookmarked page.
    val favicon: String?,

    val lastVisited: Date,

    // Optional field to store tags for categorizing bookmarks.
    val tags: String?,

    val dateAdded: Date = Date()
)
